logger:
  level: debug
  handler: text # text or json
storage:
  type: sql
  host: localhost
  port: 5432
  database: calendar
  user: postgres
  password: strong
server:
  host: localhost
  port: 8080
